//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartShopWebApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_products
    {
        public int pro_id { get; set; }
        public string pro_name { get; set; }
        public string pro_img { get; set; }
        public Nullable<double> pro_price { get; set; }
        public string pro_details { get; set; }
        public Nullable<int> pro_quantity { get; set; }
    }
}
